version: '3.7'

services: 
    api-gateway:
        image: ezazulhaq02/api-gateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - 8765:8765
        networks: 
            - currency-network

networks: 
    currency-network: